// index.js

const { Lexer } = require('./lexer');
const Parser = require('./parser');
const Interpreter = require('./interpreter');

// Sample input code
const inputCode = `
HelloWorld;
cat;
repeater;
reverse;
multiply;
`;

// Create a lexer and tokenize the input code
const lexer = new Lexer(inputCode);
const tokens = lexer.tokenize();

// Create a parser and parse the tokens
const parser = new Parser(tokens);
parser.parse();

// Create an interpreter and interpret the program
const interpreter = new Interpreter();
interpreter.interpret(/* AST generated by the parser */);
